# Project information

site_name: Finding and addressing Network Misconfigurations on AWS
site_short_name: Addressing Network Configs
site_description: 'The workshop will demonstrate how you can validate their network configuration without needing to have a deep networking background by using Inspector's Network Reachability report. You will learn how this report can help them find misconfigurations in the architecture or behaviors they might not have expected. The demo will finish with using the Network Reachability report findings integrated with other Security Services to remediate these issues.'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://github.com/mikewest82/InspectorNetworkReachability'

# Repository
repo_name: 'mikewest82/InspectorNetworkReachability'
repo_url: 'https://github.com/mikewest82/InspectorNetworkReachability'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Customization
extra:
  social:
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
link: 'https://aws.amazon.com/blogs/security/'

# Navigation
nav:
  - Overview: 'index.md'
  - 'Module 1: Environment Build and Configuration': '01-environment-setup.md'
  - 'Module 2: Running the Inspector Report': '02-running-inspector.md'
  - 'Module 3: Evaluating Findings': '03-evaluate-findings.md'
  - 'Module 4: Integration and Remediation': '04-integration-and-remediation.md'
  - 'Module 5: Cleanup': '05-cleanup.md'
  - 'Presentation Notes': 'presentation-notes.md'
  - 'Code of Conduct':  'CODE_OF_CONDUCT.md'
  - License: 'LICENSE'